; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32
board = esp-wrover-kit
framework = arduino
monitor_speed = 115200
build_src_filter = +<*> -<tests/>
board_build.partitions = partitions.csv

[env:producao]
build_src_filter = +<*> -<tests/>
lib_deps = 
	adafruit/Adafruit Thermal Printer Library@^1.4.1
	xreef/EByte LoRa E220 library@^1.0.8
	plerup/EspSoftwareSerial@^8.2.0
build_flags = 
	-DCORE_DEBUG_LEVEL=1

[env:Nextion_Display]
build_src_filter = -<*> +<tests/test_Nextion_Display.cpp>
lib_deps = 
	adafruit/Adafruit Thermal Printer Library@^1.4.1
	xreef/EByte LoRa E220 library@^1.0.8
	plerup/EspSoftwareSerial@^8.2.0

[env:HX711_Module]
build_src_filter = -<*> +<tests/test_HX711.cpp>
lib_deps = 
	adafruit/Adafruit Thermal Printer Library@^1.4.1
	xreef/EByte LoRa E220 library@^1.0.8
	plerup/EspSoftwareSerial@^8.2.0

[env:Thermal_Printer]
build_src_filter = -<*> +<tests/test_Printer.cpp>
lib_deps = 
	adafruit/Adafruit Thermal Printer Library@^1.4.1
	xreef/EByte LoRa E220 library@^1.0.8
	plerup/EspSoftwareSerial@^8.2.0

[env:Lora_E220]
build_src_filter = -<*> +<tests/test_LoraE220.cpp>
platform = espressif32
board = esp-wrover-kit
framework = arduino
monitor_speed = 115200
lib_deps = 
	adafruit/Adafruit Thermal Printer Library@^1.4.1
	xreef/EByte LoRa E220 library@^1.0.8
	plerup/EspSoftwareSerial@^8.2.0

[env:Teste_wifi]
; Include only the Teste_wifi sketch for this environment
; Exclude all source files and then include the specific test sketch located in src/tests.
build_src_filter = -<*> +<tests/Teste_wifi.cpp>
platform = espressif32
board = esp-wrover-kit
framework = arduino
monitor_speed = 115200



; Include only the EEPROM test sketch for this environment
[env:Teste_EEPROM]
build_src_filter = -<*> +<tests/test_EEPROM.cpp>
platform = espressif32
board = esp-wrover-kit
framework = arduino
monitor_speed = 115200

[env:Teste_OTA]
build_src_filter = -<*> +<tests/teste_OTA.cpp>
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200

upload_protocol = espota
upload_flags = -p 3232
upload_port = 192.168.0.226

[env:Teste_OTA_USB]
build_src_filter = -<*> +<tests/teste_OTA.cpp>
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_protocol = esptool
upload_speed = 921600


