; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[env]
platform = espressif32
board = esp-wrover-kit
framework = arduino
monitor_speed = 115200
build_src_filter = +<*> -<tests/>

# 1. Compila apenas o que está na raiz de src (main.cpp)
[env:producao]
build_src_filter = +<*> -<tests/>

# 2. Compila apenas o blink rápido
[env:Nextion_Display]
build_src_filter = -<*> +<tests/test_Nextion_Display.cpp>

# 3. Compila apenas o blink lento
[env:HX711_Module]
build_src_filter = -<*> +<tests/test_HX711.cpp>
