; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[env:main]
platform = espressif32
board = esp-wrover-kit
framework = arduino
src_dir = src
monitor_speed = 115200

[env:test_hx711]
platform = espressif32
board = esp-wrover-kit
framework = arduino
src_dir = examples/test_hx711
monitor_speed = 115200
lib_deps = bogde/HX711@^0.7.5

[env:test_nextion]
platform = espressif32
board = esp-wrover-kit
framework = arduino
src_dir = examples/test_nextion
monitor_speed = 115200

[env:test_printer]
platform = espressif32
board = esp-wrover-kit
framework = arduino
src_dir = examples/test_printer
monitor_speed = 115200

build_flags = 
    -I include